import { Geist, Geist_Mono, Playwrite_IN } from "next/font/google";
import "./globals.css";
import CustomCursor from "./components/CustomCursor";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const playwriteSans = Playwrite_IN({
  variable: "--font-playwrite-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Usman-Full stack developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${playwriteSans.variable} antialiased`}
      >
        <CustomCursor/>
        {children}
      </body>
    </html>
  );
}
